const { db } = require("../../config/firebase");

const siteExpensesCollection = db.collection("siteExpenses");
const advancesCollection = db.collection("advances");

// ─── Create Expense ───────────────────────────────────────────────────────────
//
//  Only for MANUAL site expenses entered by the user.
//  Material payment expenses are auto-created by material_service.js.
//  We block type="materialPayment" here to prevent accidental duplication.
//
exports.createExpense = async (expenseData) => {
    if (!expenseData.projectNo) {
        throw new Error("projectNo is required");
    }

    // Guard: do not allow client to manually create a materialPayment entry.
    // Those are always auto-generated by recordMaterialReceived / updateReceiptPayment.
    if (expenseData.type === "materialPayment") {
        throw new Error(
            "Material payment expenses are managed automatically. " +
            "Update the paidAmount on the material receipt instead."
        );
    }

    expenseData.createdAt = new Date().toISOString();
    expenseData.amount = Number(expenseData.amount) || 0;
    expenseData.type = expenseData.type || "siteExpense"; // explicit type tag

    // Recalculate pastExpense from DB — never trust the client value
    const snapshot = await siteExpensesCollection
        .where("projectNo", "==", expenseData.projectNo)
        .get();
    let totalPrevious = 0;
    snapshot.forEach(doc => { totalPrevious += (Number(doc.data().amount) || 0); });
    expenseData.pastExpense = totalPrevious;

    const docRef = await siteExpensesCollection.add(expenseData);
    return { expenseId: docRef.id, ...expenseData };
};


// ─── Get Expenses ─────────────────────────────────────────────────────────────
//
//  Returns all siteExpenses for a project split into:
//    manualExpenses    → entered by user
//    materialPayments  → auto-created from material receipts
//
//  The totals on the response let the Flutter screen show:
//    "Site Expenses:     ₹X"
//    "Material Payments: ₹Y"   ← auto-deducted from advance
//    "Total Expense:     ₹Z"
//    "Amount Left:       ₹(advance − Z)"
//
exports.getExpenses = async (projectNo) => {
    let query = siteExpensesCollection;
    if (projectNo) {
        query = query.where("projectNo", "==", projectNo);
    }
    const snapshot = await query.get();

    const manualExpenses = [];
    const materialPayments = [];
    let manualTotal = 0;
    let materialPayTotal = 0;

    // "2026-03-17" → "17-03-2026"
    const formatDate = (raw) => {
        if (!raw) return null;
        const d = raw.split("T")[0];          // strip time if ISO string
        const [yyyy, mm, dd] = d.split("-");
        return `${dd}-${mm}-${yyyy}`;
    };

    snapshot.forEach((doc) => {
        const data = doc.data();
        const amount = Number(data.amount) || 0;
        const rawDate = data.date || data.createdAt?.split("T")[0];

        const entry = {
            expenseId: doc.id,
            ...data,
            amount,
            remark: data.remark || data.particular || "Expense",
            date: formatDate(rawDate),   // "17-03-2026"
            amountReceived: amount,
        };

        if (data.type === "materialPayment") {
            entry.displayLabel = data.particular || `Material Payment – ${data.materialId || ""}`;
            materialPayTotal += amount;
            materialPayments.push(entry);
        } else {
            entry.displayLabel = data.particular || data.remark || "Site Expense";
            manualTotal += amount;
            manualExpenses.push(entry);
        }
    });

    const totalExpense = manualTotal + materialPayTotal;

    // Sort all lists latest first (createdAt descending)
    const sortLatestFirst = (a, b) =>
        new Date(b.createdAt || b.date) - new Date(a.createdAt || a.date);

    manualExpenses.sort(sortLatestFirst);
    materialPayments.sort(sortLatestFirst);
    const allExpenses = [...manualExpenses, ...materialPayments]
        .sort(sortLatestFirst);

    return {
        manualExpenses,
        materialPayments,
        expenses: allExpenses,   // latest entry first
        totalManualExpense: manualTotal,
        totalMaterialPayment: materialPayTotal,
        totalExpense,
    };
};


// ─── Update Expense ───────────────────────────────────────────────────────────
//
//  Only manual siteExpense records can be updated here.
//  To update a material payment, update the paidAmount on the material receipt.
//
exports.updateExpense = async (id, updateData) => {
    const docRef = siteExpensesCollection.doc(id);
    const doc = await docRef.get();
    if (!doc.exists) {
        throw new Error("Expense record not found");
    }

    // Guard: prevent manual editing of auto-generated material payment entries
    if (doc.data().type === "materialPayment") {
        throw new Error(
            "Material payment expenses cannot be edited here. " +
            "Update the paidAmount on the material receipt instead."
        );
    }

    if (updateData.amount !== undefined) updateData.amount = Number(updateData.amount);
    delete updateData.expenseId;
    delete updateData.createdAt;
    updateData.updatedAt = new Date().toISOString();

    await docRef.update(updateData);
    const updatedDoc = await docRef.get();
    return { expenseId: id, ...updatedDoc.data() };
};


// ─── Delete Expense ───────────────────────────────────────────────────────────
//
//  Only manual siteExpense records can be deleted here.
//  Material payment entries are deleted automatically when the receipt is deleted.
//
exports.deleteExpense = async (id) => {
    const docRef = siteExpensesCollection.doc(id);
    const doc = await docRef.get();
    if (!doc.exists) {
        throw new Error("Expense record not found");
    }

    // Guard: prevent manual deletion of auto-generated entries
    if (doc.data().type === "materialPayment") {
        throw new Error(
            "Material payment expenses are managed automatically. " +
            "Delete the material receipt or set paidAmount to 0 instead."
        );
    }

    await docRef.delete();
    return { message: "Expense record deleted successfully" };
};


// ─── Financial History ────────────────────────────────────────────────────────
//  Delegates to project_service which owns the single source of truth.
exports.getFinancialHistory = async (projectNo) => {
    const projectService = require("../project/project.service");
    return projectService.getFinancialHistory(projectNo);
};